use crate::lalr::{CompUnit, Diagnostic, FuncDef, GlobalDef};
use crate::llvm::async_lower::{emit_async_function, emit_async_main_driver};
use crate::llvm::layout::{StructLayout, RISCV64_DATA_LAYOUT, TARGET_LAYOUT};
use crate::llvm::module::ModuleCtx;
use crate::llvm::names::sanitize_ident;
use crate::llvm::sync::{emit_global_decl, emit_sync_function};
use std::collections::HashMap;
use std::fmt::Write;

pub const DEFAULT_RISCV_TARGET: &str = "riscv64-unknown-unknown-elf";

pub fn compile_to_llvm(ast: &CompUnit) -> String {
    compile_to_llvm_with_target(ast, DEFAULT_RISCV_TARGET)
}

pub fn try_compile_to_llvm(ast: &CompUnit) -> Result<String, Diagnostic> {
    try_compile_to_llvm_with_target(ast, DEFAULT_RISCV_TARGET)
}

pub fn compile_to_llvm_with_target(ast: &CompUnit, target_triple: &str) -> String {
    try_compile_to_llvm_with_target(ast, target_triple).unwrap_or_else(|err| panic!("{}", err))
}

pub fn try_compile_to_llvm_with_target(
    ast: &CompUnit,
    target_triple: &str,
) -> Result<String, Diagnostic> {
    ast.validate_semantics()?;
    catch_lowering_errors(|| emit_llvm_unchecked(ast, target_triple))
}

fn catch_lowering_errors<F>(f: F) -> Result<String, Diagnostic>
where
    F: FnOnce() -> Result<String, Diagnostic>,
{
    let previous_hook = std::panic::take_hook();
    std::panic::set_hook(Box::new(|_| {}));
    let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(f));
    std::panic::set_hook(previous_hook);
    result.map_err(|payload| {
        let message = if let Some(message) = payload.downcast_ref::<String>() {
            message.clone()
        } else if let Some(message) = payload.downcast_ref::<&str>() {
            (*message).to_string()
        } else {
            "unknown panic".to_string()
        };
        Diagnostic::new(format!("LLVM lowering failed: {}", message))
    })?
}

fn emit_llvm_unchecked(ast: &CompUnit, target_triple: &str) -> Result<String, Diagnostic> {
    let mut module = ModuleCtx::new();
    module.scan(ast)?;
    module.resolve_struct_layouts()?;

    let mut out = String::new();
    out.push_str("; generated by compile-sysy LLVM backend\n");
    if target_triple.starts_with("riscv64") {
        let _ = writeln!(out, "target datalayout = \"{}\"", RISCV64_DATA_LAYOUT);
    }
    let _ = writeln!(out, "target triple = \"{}\"\n", target_triple);

    for (name, layout) in stable_structs(&module.layouts) {
        let fields = layout
            .fields
            .iter()
            .map(|field| field.ty.llvm())
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(
            out,
            "%struct.{} = type {{ {} }}",
            sanitize_ident(name),
            fields
        );
    }
    if !module.layouts.is_empty() {
        out.push('\n');
    }

    out.push_str("%promise = type { i32, i32, i64, ptr, ptr, ptr, ptr, ptr, ptr }\n\n");
    let _ = writeln!(
        out,
        "declare ptr @malloc({})",
        TARGET_LAYOUT.malloc_size_type
    );
    out.push_str("declare void @free(ptr)\n");
    out.push_str("declare i32 @getint()\n");
    out.push_str("declare i32 @getch()\n");
    out.push_str("declare i32 @getarray(ptr)\n");
    out.push_str("declare void @putint(i32)\n");
    out.push_str("declare i32 @putch(i32)\n");
    out.push_str("declare void @putarray(i32, ptr)\n");
    out.push_str("declare void @starttime()\n");
    out.push_str("declare void @stoptime()\n\n");
    out.push_str("declare ptr @__sysy_promise_new(i64)\n");
    out.push_str("declare void @__sysy_promise_resolve(ptr, ptr)\n");
    out.push_str("declare ptr @__sysy_promise_result_ptr(ptr)\n");
    out.push_str("declare void @__sysy_promise_wait(ptr)\n");
    out.push_str("declare i32 @__sysy_promise_is_ready(ptr)\n");
    out.push_str("declare void @__sysy_promise_set_callback(ptr, ptr, ptr)\n");
    out.push_str("declare void @__sysy_pending_add(ptr, ptr, ptr)\n");
    out.push_str("declare void @__sysy_promise_clear_driver(ptr)\n");
    out.push_str("declare ptr @__sysy_sleep(i32)\n\n");

    for glob_def in &ast.global_defs {
        if let GlobalDef::GlobalDecl(ty, decls) = glob_def {
            emit_global_decl(&mut out, &module, ty, decls)?;
        }
    }

    for glob_def in &ast.global_defs {
        if let GlobalDef::FuncDef(func) = glob_def {
            if func.is_async && func.ident == "main" {
                let mut hidden = func.clone();
                hidden.ident = "__sysy_async_main".to_string();
                out.push_str(&emit_function(&module, &hidden)?);
                out.push_str(&emit_async_main_driver(&module, &hidden));
            } else {
                out.push_str(&emit_function(&module, func)?);
            }
        }
    }
    Ok(out)
}

fn emit_function(module: &ModuleCtx, func: &FuncDef) -> Result<String, Diagnostic> {
    if func.is_async {
        emit_async_function(module, func).map_err(Diagnostic::from)
    } else {
        emit_sync_function(module, func).map_err(Diagnostic::from)
    }
}

fn stable_structs(layouts: &HashMap<String, StructLayout>) -> Vec<(&String, &StructLayout)> {
    let mut items = layouts.iter().collect::<Vec<_>>();
    items.sort_by(|lhs, rhs| lhs.0.cmp(rhs.0));
    items
}
