use crate::lalr::{
    eval_const_exp_with, eval_param_dim, func_param_btype, BType, BinaryOp,
    CompUnit, Exp, FuncDef, FuncParam, GlobleDef, InitVal, SingleDecl, Stmt, StructDef, Type,
    UnaryOp, VarDecl,
};
use std::collections::HashMap;
use std::fmt::Write;
use std::path::Path;
use std::process::Command;

#[derive(Debug, Clone, PartialEq, Eq)]
enum LlvmType {
    I32,
    Void,
    Ptr(Box<LlvmType>),
    Struct(String),
    Array(usize, Box<LlvmType>),
    Promise(Box<LlvmType>),
}

impl LlvmType {
    fn from_btype(btype: &BType) -> Self {
        match btype {
            BType::I32 => Self::I32,
            BType::Void => Self::Void,
            BType::Struct(name) => Self::Struct(name.clone()),
            BType::Promise(inner) => Self::Promise(Box::new(Self::from_btype(inner))),
            BType::Ptr(inner) => Self::Ptr(Box::new(Self::from_btype(inner))),
            BType::Array(len, inner) => Self::Array(*len, Box::new(Self::from_btype(inner))),
        }
    }

    fn llvm(&self) -> String {
        match self {
            Self::I32 => "i32".to_string(),
            Self::Void => "void".to_string(),
            Self::Ptr(_) | Self::Promise(_) => "ptr".to_string(),
            Self::Struct(name) => format!("%struct.{}", sanitize_ident(name)),
            Self::Array(len, inner) => format!("[{} x {}]", len, inner.llvm()),
        }
    }

    fn promise_value(&self) -> LlvmType {
        match self {
            Self::Promise(inner) => (**inner).clone(),
            other => other.clone(),
        }
    }

    fn size(&self, structs: &HashMap<String, StructLayout>) -> usize {
        match self {
            Self::I32 | Self::Ptr(_) | Self::Promise(_) => 4,
            Self::Void => 0,
            Self::Array(len, inner) => len * inner.size(structs),
            Self::Struct(name) => structs
                .get(name)
                .unwrap_or_else(|| panic!("Unknown struct type {}", name))
                .size,
        }
    }

    fn align(&self, structs: &HashMap<String, StructLayout>) -> usize {
        match self {
            Self::I32 | Self::Ptr(_) | Self::Promise(_) => 4,
            Self::Void => 1,
            Self::Array(_, inner) => inner.align(structs),
            Self::Struct(name) => structs
                .get(name)
                .unwrap_or_else(|| panic!("Unknown struct type {}", name))
                .align,
        }
    }

    fn is_void(&self) -> bool {
        matches!(self, Self::Void)
    }
}

#[derive(Debug, Clone)]
struct FieldLayout {
    name: String,
    ty: LlvmType,
    index: usize,
}

#[derive(Debug, Clone)]
struct StructLayout {
    fields: Vec<FieldLayout>,
    size: usize,
    align: usize,
}

#[derive(Debug, Clone)]
struct FuncSig {
    ret: LlvmType,
    is_async: bool,
}

#[derive(Debug, Clone)]
struct VarInfo {
    ptr: String,
    ty: LlvmType,
}

#[derive(Debug, Clone)]
struct Value {
    name: String,
    ty: LlvmType,
}

#[derive(Debug, Clone)]
struct LValue {
    ptr: String,
    ty: LlvmType,
}

#[derive(Debug, Default)]
struct ModuleCtx {
    structs: HashMap<String, StructDef>,
    layouts: HashMap<String, StructLayout>,
    funcs: HashMap<String, FuncSig>,
    globals: HashMap<String, LlvmType>,
    constants: HashMap<String, i32>,
}

#[derive(Debug)]
struct FunctionCtx<'a> {
    module: &'a ModuleCtx,
    vars: Vec<HashMap<String, VarInfo>>,
    lines: Vec<String>,
    tmp_counter: usize,
    label_counter: usize,
    current_terminated: bool,
    is_async: bool,
    promise_ptr: Option<String>,
}

pub fn compile_to_llvm(ast: &CompUnit) -> String {
    ast.validate_async_syntax()
        .unwrap_or_else(|err| panic!("{}", err));
    let mut module = ModuleCtx::new();
    module.scan(ast);
    module.resolve_struct_layouts();

    let mut out = String::new();
    out.push_str("; generated by compile-sysy LLVM backend\n");
    out.push_str("target triple = \"riscv32-unknown-unknown-elf\"\n\n");

    for (name, layout) in stable_structs(&module.layouts) {
        let fields = layout
            .fields
            .iter()
            .map(|field| field.ty.llvm())
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(out, "%struct.{} = type {{ {} }}", sanitize_ident(name), fields);
    }
    if !module.layouts.is_empty() {
        out.push('\n');
    }

    out.push_str("%promise.i32 = type { i32, i32 }\n");
    out.push_str("%promise.void = type { i32 }\n\n");
    out.push_str("declare ptr @malloc(i32)\n");
    out.push_str("declare void @free(ptr)\n");
    out.push_str("declare i32 @getint()\n");
    out.push_str("declare i32 @getch()\n");
    out.push_str("declare i32 @getarray(ptr)\n");
    out.push_str("declare void @putint(i32)\n");
    out.push_str("declare i32 @putch(i32)\n");
    out.push_str("declare void @putarray(i32, ptr)\n");
    out.push_str("declare void @starttime()\n");
    out.push_str("declare void @stoptime()\n\n");
    out.push_str(PROMISE_RUNTIME);

    for glob_def in &ast.glob_defs {
        if let GlobleDef::GlobleDecl(ty, decls) = glob_def {
            emit_global_decl(&mut out, &module, ty, decls);
        }
    }

    for glob_def in &ast.glob_defs {
        if let GlobleDef::FuncDef(func) = glob_def {
            if func.is_async && func.ident == "main" {
                let mut hidden = func.clone();
                hidden.ident = "__sysy_async_main".to_string();
                out.push_str(&emit_function(&module, &hidden));
                out.push_str(&emit_async_main_driver(&module, &hidden));
            } else {
                out.push_str(&emit_function(&module, func));
            }
        }
    }
    out
}

pub fn compile_llvm_to_riscv_asm(llvm_ir: &str, output: &Path) -> std::io::Result<()> {
    let mut input = std::env::temp_dir();
    let unique = format!(
        "compile_sysy_{}_{}.ll",
        std::process::id(),
        unique_suffix()
    );
    input.push(unique);
    std::fs::write(&input, llvm_ir)?;
    let clang = std::env::var("SYSY_CLANG").unwrap_or_else(|_| default_clang());
    let status = Command::new(&clang)
        .arg("-target")
        .arg("riscv32-unknown-elf")
        .arg("-march=rv32im")
        .arg("-mabi=ilp32")
        .arg("-S")
        .arg("-ffreestanding")
        .arg("-fno-addrsig")
        .arg("-nostdlib")
        .arg("-O0")
        .arg(&input)
        .arg("-o")
        .arg(output)
        .status()?;
    let _ = std::fs::remove_file(&input);
    if !status.success() {
        return Err(std::io::Error::new(
            std::io::ErrorKind::Other,
            format!("{} failed to compile LLVM IR to RISC-V assembly", clang),
        ));
    }
    Ok(())
}

impl ModuleCtx {
    fn new() -> Self {
        Self::default()
    }

    fn scan(&mut self, ast: &CompUnit) {
        for glob_def in &ast.glob_defs {
            if let GlobleDef::StructDef(def) = glob_def {
                self.structs.insert(def.name.clone(), def.clone());
            }
        }
        self.insert_runtime_funcs();
        for glob_def in &ast.glob_defs {
            match glob_def {
                GlobleDef::FuncDef(func) => {
                    let ret = type_to_llvm(&func.func_type);
                    self.funcs.insert(
                        func.ident.clone(),
                        FuncSig {
                            ret,
                            is_async: func.is_async,
                        },
                    );
                }
                GlobleDef::GlobleDecl(ty, decls) => {
                    for decl in decls {
                        let name = var_decl_name(&decl.var);
                        let value_ty = decl_type(ty, &decl.var, self);
                        if matches!(ty, Type::Const(_)) && matches!(value_ty, LlvmType::I32) {
                            if let Some(init) = &decl.init {
                                if let Some(value) = init_const(init, self) {
                                    self.constants.insert(name, value);
                                }
                            }
                        } else {
                            self.globals.insert(name, value_ty);
                        }
                    }
                }
                GlobleDef::StructDef(_) => {}
            }
        }
    }

    fn insert_runtime_funcs(&mut self) {
        let i32_ty = LlvmType::I32;
        let void_ty = LlvmType::Void;
        let ptr_i32 = LlvmType::Ptr(Box::new(LlvmType::I32));
        for (name, ret, _params) in [
            ("getint", i32_ty.clone(), vec![]),
            ("getch", i32_ty.clone(), vec![]),
            ("getarray", i32_ty.clone(), vec![ptr_i32.clone()]),
            ("putint", void_ty.clone(), vec![i32_ty.clone()]),
            ("putch", i32_ty.clone(), vec![i32_ty.clone()]),
            ("putarray", void_ty.clone(), vec![i32_ty.clone(), ptr_i32]),
            ("starttime", void_ty.clone(), vec![]),
            ("stoptime", void_ty.clone(), vec![]),
        ] {
            self.funcs.insert(
                name.to_string(),
                FuncSig {
                    ret,
                    is_async: false,
                },
            );
        }
    }

    fn resolve_struct_layouts(&mut self) {
        let names = self.structs.keys().cloned().collect::<Vec<_>>();
        for name in names {
            self.ensure_struct_layout(&name, &mut Vec::new());
        }
    }

    fn ensure_struct_layout(&mut self, name: &str, visiting: &mut Vec<String>) -> StructLayout {
        if let Some(layout) = self.layouts.get(name) {
            return layout.clone();
        }
        if visiting.iter().any(|item| item == name) {
            panic!("Cyclic struct definition detected: {}", name);
        }
        visiting.push(name.to_string());
        let def = self
            .structs
            .get(name)
            .unwrap_or_else(|| panic!("Unknown struct type {}", name))
            .clone();
        let mut fields = Vec::new();
        let mut offset = 0usize;
        let mut align = 4usize;
        for field in &def.fields {
            for decl in &field.decls {
                let ty = decl_type(&field.ty, &decl.var, self);
                if let LlvmType::Struct(inner) = &ty {
                    self.ensure_struct_layout(inner, visiting);
                }
                let field_align = ty.align(&self.layouts);
                let field_size = ty.size(&self.layouts);
                align = align.max(field_align);
                offset = align_up(offset, field_align);
                let index = fields.len();
                fields.push(FieldLayout {
                    name: var_decl_name(&decl.var),
                    ty,
                    index,
                });
                offset += field_size;
            }
        }
        let size = align_up(offset, align);
        visiting.pop();
        let layout = StructLayout {
            fields,
            size,
            align,
        };
        self.layouts.insert(name.to_string(), layout.clone());
        layout
    }

    fn field(&self, struct_name: &str, field_name: &str) -> &FieldLayout {
        self.layouts
            .get(struct_name)
            .unwrap_or_else(|| panic!("Unknown struct type {}", struct_name))
            .fields
            .iter()
            .find(|field| field.name == field_name)
            .unwrap_or_else(|| panic!("Struct {} has no field {}", struct_name, field_name))
    }
}

impl<'a> FunctionCtx<'a> {
    fn new(module: &'a ModuleCtx, _ret_ty: LlvmType, is_async: bool) -> Self {
        Self {
            module,
            vars: vec![HashMap::new()],
            lines: Vec::new(),
            tmp_counter: 0,
            label_counter: 0,
            current_terminated: false,
            is_async,
            promise_ptr: None,
        }
    }

    fn push_scope(&mut self) {
        self.vars.push(HashMap::new());
    }

    fn pop_scope(&mut self) {
        self.vars.pop();
    }

    fn insert_var(&mut self, name: String, info: VarInfo) {
        self.vars
            .last_mut()
            .expect("No active variable scope")
            .insert(name, info);
    }

    fn lookup_var(&self, name: &str) -> Option<&VarInfo> {
        self.vars.iter().rev().find_map(|scope| scope.get(name))
    }

    fn tmp(&mut self) -> String {
        let name = format!("%t{}", self.tmp_counter);
        self.tmp_counter += 1;
        name
    }

    fn label(&mut self, prefix: &str) -> String {
        let label = format!("{}.{}", prefix, self.label_counter);
        self.label_counter += 1;
        label
    }

    fn emit(&mut self, line: impl Into<String>) {
        self.lines.push(line.into());
    }

    fn emit_label(&mut self, label: &str) {
        self.lines.push(format!("{}:", label));
        self.current_terminated = false;
    }

    fn terminate(&mut self, line: impl Into<String>) {
        if !self.current_terminated {
            self.emit(line);
            self.current_terminated = true;
        }
    }

    fn alloca(&mut self, ty: &LlvmType) -> String {
        let ptr = self.tmp();
        self.emit(format!("  {} = alloca {}", ptr, ty.llvm()));
        ptr
    }

    fn load(&mut self, ptr: &str, ty: &LlvmType) -> Value {
        let val = self.tmp();
        self.emit(format!("  {} = load {}, ptr {}", val, ty.llvm(), ptr));
        Value {
            name: val,
            ty: ty.clone(),
        }
    }

    fn store(&mut self, value: &Value, ptr: &str) {
        self.emit(format!(
            "  store {} {}, ptr {}",
            value.ty.llvm(),
            value.name,
            ptr
        ));
    }

    fn default_value(&mut self, ty: &LlvmType) -> Value {
        match ty {
            LlvmType::I32 => Value {
                name: "0".to_string(),
                ty: LlvmType::I32,
            },
            LlvmType::Ptr(_) | LlvmType::Promise(_) => Value {
                name: "null".to_string(),
                ty: ty.clone(),
            },
            other => panic!("No scalar default value for {:?}", other),
        }
    }

    fn promise_new(&mut self, value_ty: &LlvmType) -> Value {
        match value_ty {
            LlvmType::Void => {
                let ptr = self.tmp();
                self.emit(format!("  {} = call ptr @__sysy_promise_new_void()", ptr));
                Value {
                    name: ptr,
                    ty: LlvmType::Promise(Box::new(LlvmType::Void)),
                }
            }
            LlvmType::I32 => {
                let ptr = self.tmp();
                self.emit(format!("  {} = call ptr @__sysy_promise_new_i32()", ptr));
                Value {
                    name: ptr,
                    ty: LlvmType::Promise(Box::new(LlvmType::I32)),
                }
            }
            other => panic!("Promise value type {:?} is not supported yet", other),
        }
    }

    fn promise_resolve(&mut self, promise: &str, value: Option<&Value>) {
        match value {
            Some(value) if matches!(value.ty, LlvmType::I32) => self.emit(format!(
                "  call void @__sysy_promise_resolve_i32(ptr {}, i32 {})",
                promise, value.name
            )),
            None => self.emit(format!(
                "  call void @__sysy_promise_resolve_void(ptr {})",
                promise
            )),
            Some(other) => panic!("Promise resolve for {:?} is not supported", other.ty),
        }
    }

    fn promise_wait(&mut self, promise: Value) -> Value {
        let value_ty = promise.ty.promise_value();
        match value_ty {
            LlvmType::I32 => {
                let out = self.tmp();
                self.emit(format!(
                    "  {} = call i32 @__sysy_promise_wait_i32(ptr {})",
                    out, promise.name
                ));
                Value {
                    name: out,
                    ty: LlvmType::I32,
                }
            }
            LlvmType::Void => {
                self.emit(format!(
                    "  call void @__sysy_promise_wait_void(ptr {})",
                    promise.name
                ));
                Value {
                    name: "0".to_string(),
                    ty: LlvmType::Void,
                }
            }
            other => panic!("Promise.wait for {:?} is not supported", other),
        }
    }
}

fn emit_function(module: &ModuleCtx, func: &FuncDef) -> String {
    let original_ret = type_to_llvm(&func.func_type);
    let llvm_ret = if func.is_async {
        LlvmType::Promise(Box::new(original_ret.clone()))
    } else {
        original_ret.clone()
    };
    let params = func
        .func_params
        .iter()
        .map(|param| (param.name.clone(), LlvmType::from_btype(&param_resolved_btype(param, module))))
        .collect::<Vec<_>>();
    let mut ctx = FunctionCtx::new(module, original_ret.clone(), func.is_async);
    let param_sig = params
        .iter()
        .enumerate()
        .map(|(idx, (_, ty))| format!("{} %arg{}", ty.llvm(), idx))
        .collect::<Vec<_>>()
        .join(", ");
    let mut out = String::new();
    let _ = writeln!(
        out,
        "define {} @{}({}) {{",
        llvm_ret.llvm(),
        sanitize_ident(&func.ident),
        param_sig
    );
    ctx.emit_label("entry");
    if func.is_async {
        let promise = ctx.promise_new(&original_ret);
        ctx.promise_ptr = Some(promise.name);
    }
    for (idx, (name, ty)) in params.iter().enumerate() {
        let ptr = ctx.alloca(ty);
        ctx.emit(format!("  store {} %arg{}, ptr {}", ty.llvm(), idx, ptr));
        ctx.insert_var(
            name.clone(),
            VarInfo {
                ptr,
                ty: ty.clone(),
            },
        );
    }
    emit_stmts(&mut ctx, &func.block);
    if !ctx.current_terminated {
        if func.is_async {
            let promise = ctx.promise_ptr.clone().unwrap();
            if original_ret.is_void() {
                ctx.promise_resolve(&promise, None);
            } else {
                let value = ctx.default_value(&original_ret);
                ctx.promise_resolve(&promise, Some(&value));
            }
            ctx.terminate(format!("  ret ptr {}", promise));
        } else if original_ret.is_void() {
            ctx.terminate("  ret void".to_string());
        } else {
            let value = ctx.default_value(&original_ret);
            ctx.terminate(format!("  ret {} {}", original_ret.llvm(), value.name));
        }
    }
    for line in ctx.lines {
        let _ = writeln!(out, "{}", line);
    }
    out.push_str("}\n\n");
    out
}

fn emit_async_main_driver(module: &ModuleCtx, _hidden: &FuncDef) -> String {
    let mut ctx = FunctionCtx::new(module, LlvmType::I32, false);
    let mut out = String::new();
    out.push_str("define i32 @main() {\n");
    ctx.emit_label("entry");
    let call = call_function(&mut ctx, "__sysy_async_main", &[]);
    let waited = ctx.promise_wait(call);
    if matches!(waited.ty, LlvmType::Void) {
        ctx.terminate("  ret i32 0".to_string());
    } else {
        ctx.terminate(format!("  ret i32 {}", waited.name));
    }
    for line in ctx.lines {
        let _ = writeln!(out, "{}", line);
    }
    out.push_str("}\n\n");
    out
}

fn emit_global_decl(out: &mut String, module: &ModuleCtx, ty: &Type, decls: &[SingleDecl]) {
    for decl in decls {
        let name = var_decl_name(&decl.var);
        let value_ty = decl_type(ty, &decl.var, module);
        if module.constants.contains_key(&name) {
            continue;
        }
        let init = match (&value_ty, &decl.init) {
            (LlvmType::I32, Some(init)) => init_const(init, module).unwrap_or(0).to_string(),
            (LlvmType::I32, None) => "0".to_string(),
            _ => "zeroinitializer".to_string(),
        };
        let _ = writeln!(
            out,
            "@{} = global {} {}",
            sanitize_ident(&name),
            value_ty.llvm(),
            init
        );
    }
    if !decls.is_empty() {
        out.push('\n');
    }
}

fn emit_stmts(ctx: &mut FunctionCtx<'_>, stmts: &[Stmt]) {
    ctx.push_scope();
    for stmt in stmts {
        if ctx.current_terminated {
            break;
        }
        emit_stmt(ctx, stmt);
    }
    ctx.pop_scope();
}

fn emit_stmt(ctx: &mut FunctionCtx<'_>, stmt: &Stmt) {
    match stmt {
        Stmt::Block(stmts) => emit_stmts(ctx, stmts),
        Stmt::Assign(lhs, rhs) => {
            let value = emit_exp(ctx, rhs);
            let lvalue = emit_lvalue(ctx, lhs);
            ctx.store(&value, &lvalue.ptr);
        }
        Stmt::Decl(ty, decls) => {
            for decl in decls {
                let name = var_decl_name(&decl.var);
                let value_ty = decl_type(ty, &decl.var, ctx.module);
                if matches!(ty, Type::Const(_)) && matches!(value_ty, LlvmType::I32) {
                    if let Some(init) = &decl.init {
                        if let Some(value) = init_const(init, ctx.module) {
                            ctx.module.constants.get(&name).or(Some(&value));
                        }
                    }
                    continue;
                }
                let ptr = ctx.alloca(&value_ty);
                ctx.insert_var(
                    name,
                    VarInfo {
                        ptr: ptr.clone(),
                        ty: value_ty.clone(),
                    },
                );
                if let Some(init) = &decl.init {
                    init_store(ctx, init, &value_ty, &ptr);
                }
            }
        }
        Stmt::Exp(exp) => {
            let _ = emit_exp(ctx, exp);
        }
        Stmt::PromiseWait(exp) => {
            let promise = emit_exp(ctx, exp);
            let _ = ctx.promise_wait(promise);
        }
        Stmt::Return(Some(exp)) => {
            let value = emit_exp(ctx, exp);
            if ctx.is_async {
                let promise = ctx.promise_ptr.clone().unwrap();
                if value.ty.is_void() {
                    ctx.promise_resolve(&promise, None);
                } else {
                    ctx.promise_resolve(&promise, Some(&value));
                }
                ctx.terminate(format!("  ret ptr {}", promise));
            } else {
                ctx.terminate(format!("  ret {} {}", value.ty.llvm(), value.name));
            }
        }
        Stmt::Return(None) => {
            if ctx.is_async {
                let promise = ctx.promise_ptr.clone().unwrap();
                ctx.promise_resolve(&promise, None);
                ctx.terminate(format!("  ret ptr {}", promise));
            } else {
                ctx.terminate("  ret void".to_string());
            }
        }
        Stmt::If(cond, then_stmt) => {
            let then_label = ctx.label("if.then");
            let end_label = ctx.label("if.end");
            emit_cond_br(ctx, cond, &then_label, &end_label);
            ctx.emit_label(&then_label);
            emit_stmt(ctx, then_stmt);
            if !ctx.current_terminated {
                ctx.terminate(format!("  br label %{}", end_label));
            }
            ctx.emit_label(&end_label);
        }
        Stmt::IfElse(cond, then_stmt, else_stmt) => {
            let then_label = ctx.label("if.then");
            let else_label = ctx.label("if.else");
            let end_label = ctx.label("if.end");
            emit_cond_br(ctx, cond, &then_label, &else_label);
            ctx.emit_label(&then_label);
            emit_stmt(ctx, then_stmt);
            if !ctx.current_terminated {
                ctx.terminate(format!("  br label %{}", end_label));
            }
            ctx.emit_label(&else_label);
            emit_stmt(ctx, else_stmt);
            if !ctx.current_terminated {
                ctx.terminate(format!("  br label %{}", end_label));
            }
            ctx.emit_label(&end_label);
        }
        Stmt::While(cond, body) => {
            let cond_label = ctx.label("while.cond");
            let body_label = ctx.label("while.body");
            let end_label = ctx.label("while.end");
            ctx.terminate(format!("  br label %{}", cond_label));
            ctx.emit_label(&cond_label);
            emit_cond_br(ctx, cond, &body_label, &end_label);
            ctx.emit_label(&body_label);
            emit_stmt(ctx, body);
            if !ctx.current_terminated {
                ctx.terminate(format!("  br label %{}", cond_label));
            }
            ctx.emit_label(&end_label);
        }
        Stmt::Break | Stmt::Continue => {
            panic!("break/continue are not supported by the LLVM backend yet")
        }
        Stmt::Empty => {}
    }
}

fn emit_exp(ctx: &mut FunctionCtx<'_>, exp: &Exp) -> Value {
    match exp {
        Exp::Number(value) => Value {
            name: value.to_string(),
            ty: LlvmType::I32,
        },
        Exp::Ident(name) => {
            if let Some(value) = ctx.module.constants.get(name) {
                return Value {
                    name: value.to_string(),
                    ty: LlvmType::I32,
                };
            }
            if let Some(var) = ctx.lookup_var(name).cloned() {
                match var.ty {
                    LlvmType::Struct(_) | LlvmType::Array(_, _) => Value {
                        name: var.ptr,
                        ty: LlvmType::Ptr(Box::new(var.ty)),
                    },
                    _ => ctx.load(&var.ptr, &var.ty),
                }
            } else if let Some(global_ty) = ctx.module.globals.get(name).cloned() {
                match global_ty {
                    LlvmType::Struct(_) | LlvmType::Array(_, _) => Value {
                        name: format!("@{}", sanitize_ident(name)),
                        ty: LlvmType::Ptr(Box::new(global_ty)),
                    },
                    _ => ctx.load(&format!("@{}", sanitize_ident(name)), &global_ty),
                }
            } else {
                panic!("Unknown identifier {}", name);
            }
        }
        Exp::UnaryExp(UnaryOp::Addr, inner) => {
            let lvalue = emit_lvalue(ctx, inner);
            Value {
                name: lvalue.ptr,
                ty: LlvmType::Ptr(Box::new(lvalue.ty)),
            }
        }
        Exp::UnaryExp(UnaryOp::Deref, inner) => {
            let ptr = emit_exp(ctx, inner);
            match ptr.ty {
                LlvmType::Ptr(inner_ty) => ctx.load(&ptr.name, &inner_ty),
                other => panic!("Cannot dereference {:?}", other),
            }
        }
        Exp::UnaryExp(op, inner) => {
            let value = emit_exp(ctx, inner);
            match op {
                UnaryOp::Pos => value,
                UnaryOp::Neg => {
                    let out = ctx.tmp();
                    ctx.emit(format!("  {} = sub i32 0, {}", out, value.name));
                    Value {
                        name: out,
                        ty: LlvmType::I32,
                    }
                }
                UnaryOp::Not => {
                    let cmp = ctx.tmp();
                    let out = ctx.tmp();
                    ctx.emit(format!("  {} = icmp eq i32 {}, 0", cmp, value.name));
                    ctx.emit(format!("  {} = zext i1 {} to i32", out, cmp));
                    Value {
                        name: out,
                        ty: LlvmType::I32,
                    }
                }
                UnaryOp::Addr | UnaryOp::Deref => unreachable!(),
            }
        }
        Exp::BinaryExp(op, lhs, rhs) => emit_binary(ctx, op, lhs, rhs),
        Exp::New(ty) => {
            let value_ty = LlvmType::from_btype(ty);
            let ptr = ctx.tmp();
            ctx.emit(format!(
                "  {} = call ptr @malloc(i32 {})",
                ptr,
                value_ty.size(&ctx.module.layouts)
            ));
            Value {
                name: ptr,
                ty: LlvmType::Ptr(Box::new(value_ty)),
            }
        }
        Exp::Await(inner) => {
            let promise = emit_exp(ctx, inner);
            ctx.promise_wait(promise)
        }
        Exp::Sleep(duration) => {
            let value = emit_exp(ctx, duration);
            let promise = ctx.tmp();
            ctx.emit(format!("  {} = call ptr @__sysy_sleep(i32 {})", promise, value.name));
            Value {
                name: promise,
                ty: LlvmType::Promise(Box::new(LlvmType::Void)),
            }
        }
        Exp::PromiseWait(inner) => {
            let promise = emit_exp(ctx, inner);
            ctx.promise_wait(promise)
        }
        Exp::FuncCall(name, args) => {
            let values = args.iter().map(|arg| emit_exp(ctx, arg)).collect::<Vec<_>>();
            call_function(ctx, name, &values)
        }
        Exp::ArrGet(_, _) | Exp::Field(_, _) | Exp::PtrField(_, _) => {
            let lvalue = emit_lvalue(ctx, exp);
            match lvalue.ty {
                LlvmType::Struct(_) | LlvmType::Array(_, _) => Value {
                    name: lvalue.ptr,
                    ty: LlvmType::Ptr(Box::new(lvalue.ty)),
                },
                _ => ctx.load(&lvalue.ptr, &lvalue.ty),
            }
        }
    }
}

fn emit_binary(ctx: &mut FunctionCtx<'_>, op: &BinaryOp, lhs: &Exp, rhs: &Exp) -> Value {
    let l = emit_exp(ctx, lhs);
    let r = emit_exp(ctx, rhs);
    let out = ctx.tmp();
    match op {
        BinaryOp::Add => ctx.emit(format!("  {} = add i32 {}, {}", out, l.name, r.name)),
        BinaryOp::Sub => ctx.emit(format!("  {} = sub i32 {}, {}", out, l.name, r.name)),
        BinaryOp::Mul => ctx.emit(format!("  {} = mul i32 {}, {}", out, l.name, r.name)),
        BinaryOp::Div => ctx.emit(format!("  {} = sdiv i32 {}, {}", out, l.name, r.name)),
        BinaryOp::Mod => ctx.emit(format!("  {} = srem i32 {}, {}", out, l.name, r.name)),
        BinaryOp::And => {
            let lb = ctx.tmp();
            let rb = ctx.tmp();
            ctx.emit(format!("  {} = icmp ne i32 {}, 0", lb, l.name));
            ctx.emit(format!("  {} = icmp ne i32 {}, 0", rb, r.name));
            let and_tmp = ctx.tmp();
            ctx.emit(format!("  {} = and i1 {}, {}", and_tmp, lb, rb));
            ctx.emit(format!("  {} = zext i1 {} to i32", out, and_tmp));
        }
        BinaryOp::Or => {
            let lb = ctx.tmp();
            let rb = ctx.tmp();
            ctx.emit(format!("  {} = icmp ne i32 {}, 0", lb, l.name));
            ctx.emit(format!("  {} = icmp ne i32 {}, 0", rb, r.name));
            let or_tmp = ctx.tmp();
            ctx.emit(format!("  {} = or i1 {}, {}", or_tmp, lb, rb));
            ctx.emit(format!("  {} = zext i1 {} to i32", out, or_tmp));
        }
        cmp => {
            let pred = match cmp {
                BinaryOp::Lt => "slt",
                BinaryOp::Gt => "sgt",
                BinaryOp::Le => "sle",
                BinaryOp::Ge => "sge",
                BinaryOp::Eq => "eq",
                BinaryOp::Ne => "ne",
                _ => unreachable!(),
            };
            let cmp_tmp = ctx.tmp();
            ctx.emit(format!(
                "  {} = icmp {} i32 {}, {}",
                cmp_tmp, pred, l.name, r.name
            ));
            ctx.emit(format!("  {} = zext i1 {} to i32", out, cmp_tmp));
        }
    }
    Value {
        name: out,
        ty: LlvmType::I32,
    }
}

fn emit_lvalue(ctx: &mut FunctionCtx<'_>, exp: &Exp) -> LValue {
    match exp {
        Exp::Ident(name) => {
            if let Some(var) = ctx.lookup_var(name).cloned() {
                LValue {
                    ptr: var.ptr,
                    ty: var.ty,
                }
            } else if let Some(ty) = ctx.module.globals.get(name).cloned() {
                LValue {
                    ptr: format!("@{}", sanitize_ident(name)),
                    ty,
                }
            } else {
                panic!("Unknown lvalue {}", name);
            }
        }
        Exp::UnaryExp(UnaryOp::Deref, inner) => {
            let ptr = emit_exp(ctx, inner);
            match ptr.ty {
                LlvmType::Ptr(inner_ty) => LValue {
                    ptr: ptr.name,
                    ty: *inner_ty,
                },
                other => panic!("Cannot dereference lvalue {:?}", other),
            }
        }
        Exp::ArrGet(base, index) => {
            let base_lv = emit_lvalue(ctx, base);
            let idx = emit_exp(ctx, index);
            let elem_ty = match &base_lv.ty {
                LlvmType::Array(_, inner) => (**inner).clone(),
                LlvmType::Ptr(inner) => (**inner).clone(),
                other => panic!("Cannot index into {:?}", other),
            };
            let gep = ctx.tmp();
            match &base_lv.ty {
                LlvmType::Array(_, _) => ctx.emit(format!(
                    "  {} = getelementptr inbounds {}, ptr {}, i32 0, i32 {}",
                    gep,
                    base_lv.ty.llvm(),
                    base_lv.ptr,
                    idx.name
                )),
                LlvmType::Ptr(_) => {
                    let loaded_base = ctx.load(&base_lv.ptr, &base_lv.ty);
                    ctx.emit(format!(
                        "  {} = getelementptr inbounds {}, ptr {}, i32 {}",
                        gep,
                        elem_ty.llvm(),
                        loaded_base.name,
                        idx.name
                    ));
                }
                _ => unreachable!(),
            }
            LValue {
                ptr: gep,
                ty: elem_ty,
            }
        }
        Exp::Field(base, field_name) => {
            let base_lv = emit_lvalue(ctx, base);
            let struct_name = match &base_lv.ty {
                LlvmType::Struct(name) => name.clone(),
                other => panic!("Cannot access field on {:?}", other),
            };
            let field = ctx.module.field(&struct_name, field_name);
            let gep = ctx.tmp();
            ctx.emit(format!(
                "  {} = getelementptr inbounds {}, ptr {}, i32 0, i32 {}",
                gep,
                LlvmType::Struct(struct_name).llvm(),
                base_lv.ptr,
                field.index
            ));
            LValue {
                ptr: gep,
                ty: field.ty.clone(),
            }
        }
        Exp::PtrField(base, field_name) => {
            let base_value = emit_exp(ctx, base);
            let struct_name = match &base_value.ty {
                LlvmType::Ptr(inner) => match &**inner {
                    LlvmType::Struct(name) => name.clone(),
                    other => panic!("Cannot access pointer field through {:?}", other),
                },
                other => panic!("Cannot access pointer field through {:?}", other),
            };
            let field = ctx.module.field(&struct_name, field_name);
            let gep = ctx.tmp();
            ctx.emit(format!(
                "  {} = getelementptr inbounds {}, ptr {}, i32 0, i32 {}",
                gep,
                LlvmType::Struct(struct_name).llvm(),
                base_value.name,
                field.index
            ));
            LValue {
                ptr: gep,
                ty: field.ty.clone(),
            }
        }
        other => panic!("Expression {:?} is not assignable", other),
    }
}

fn emit_cond_br(ctx: &mut FunctionCtx<'_>, cond: &Exp, then_label: &str, else_label: &str) {
    let value = emit_exp(ctx, cond);
    let cmp = ctx.tmp();
    ctx.emit(format!("  {} = icmp ne i32 {}, 0", cmp, value.name));
    ctx.terminate(format!(
        "  br i1 {}, label %{}, label %{}",
        cmp, then_label, else_label
    ));
}

fn call_function(ctx: &mut FunctionCtx<'_>, name: &str, args: &[Value]) -> Value {
    let sig = ctx
        .module
        .funcs
        .get(name)
        .unwrap_or_else(|| panic!("Unknown function {}", name))
        .clone();
    let ret_ty = if sig.is_async {
        LlvmType::Promise(Box::new(sig.ret.clone()))
    } else {
        sig.ret.clone()
    };
    let args_text = args
        .iter()
        .map(|arg| format!("{} {}", arg.ty.llvm(), arg.name))
        .collect::<Vec<_>>()
        .join(", ");
    if ret_ty.is_void() {
        ctx.emit(format!("  call void @{}({})", sanitize_ident(name), args_text));
        Value {
            name: "0".to_string(),
            ty: LlvmType::Void,
        }
    } else {
        let out = ctx.tmp();
        ctx.emit(format!(
            "  {} = call {} @{}({})",
            out,
            ret_ty.llvm(),
            sanitize_ident(name),
            args_text
        ));
        Value {
            name: out,
            ty: ret_ty,
        }
    }
}

fn init_store(ctx: &mut FunctionCtx<'_>, init: &InitVal, ty: &LlvmType, ptr: &str) {
    match init {
        InitVal::Exp(exp) => {
            let value = emit_exp(ctx, exp);
            ctx.emit(format!("  store {} {}, ptr {}", ty.llvm(), value.name, ptr));
        }
        InitVal::Arr(items) => {
            if let LlvmType::Array(_, inner) = ty {
                for (idx, item) in items.iter().enumerate() {
                    let elem_ptr = ctx.tmp();
                    ctx.emit(format!(
                        "  {} = getelementptr inbounds {}, ptr {}, i32 0, i32 {}",
                        elem_ptr,
                        ty.llvm(),
                        ptr,
                        idx
                    ));
                    init_store(ctx, item, inner, &elem_ptr);
                }
            }
        }
    }
}

fn type_to_llvm(ty: &Type) -> LlvmType {
    match ty {
        Type::BType(btype) | Type::Const(btype) => LlvmType::from_btype(btype),
    }
}

fn decl_type(ty: &Type, var: &VarDecl, module: &ModuleCtx) -> LlvmType {
    let base = type_to_llvm(ty);
    apply_var_dims(base, var, module)
}

fn apply_var_dims(base: LlvmType, var: &VarDecl, module: &ModuleCtx) -> LlvmType {
    match var {
        VarDecl::Ident(_) => base,
        VarDecl::Array(inner, len) => {
            let inner_ty = apply_var_dims(base, inner, module);
            let len = eval_const_exp_with(len, &|name| module.constants.get(name).copied())
                .expect("Array length must be a constant expression");
            LlvmType::Array(len as usize, Box::new(inner_ty))
        }
    }
}

fn param_resolved_btype(param: &FuncParam, module: &ModuleCtx) -> BType {
    if let Some(dims) = &param.array_dims {
        let dims = dims
            .iter()
            .map(|dim| eval_param_dim(dim, &|name| module.constants.get(name).copied()))
            .collect::<Vec<_>>();
        func_param_btype(param.btype.clone(), dims)
    } else {
        param.btype.clone()
    }
}

fn var_decl_name(var: &VarDecl) -> String {
    match var {
        VarDecl::Ident(name) => name.clone(),
        VarDecl::Array(inner, _) => var_decl_name(inner),
    }
}

fn init_const(init: &InitVal, module: &ModuleCtx) -> Option<i32> {
    match init {
        InitVal::Exp(exp) => eval_const_exp_with(exp, &|name| module.constants.get(name).copied()),
        InitVal::Arr(_) => None,
    }
}

fn stable_structs(layouts: &HashMap<String, StructLayout>) -> Vec<(&String, &StructLayout)> {
    let mut items = layouts.iter().collect::<Vec<_>>();
    items.sort_by(|lhs, rhs| lhs.0.cmp(rhs.0));
    items
}

fn align_up(value: usize, align: usize) -> usize {
    if align == 0 {
        value
    } else {
        (value + align - 1) / align * align
    }
}

fn sanitize_ident(name: &str) -> String {
    name.chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '_' || ch == '.' {
                ch
            } else {
                '_'
            }
        })
        .collect()
}

fn unique_suffix() -> u128 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|duration| duration.as_nanos())
        .unwrap_or(0)
}

fn default_clang() -> String {
    if Command::new("clang-18")
        .arg("--version")
        .output()
        .is_ok_and(|output| output.status.success())
    {
        "clang-18".to_string()
    } else {
        "clang".to_string()
    }
}

const PROMISE_RUNTIME: &str = r#"define ptr @__sysy_promise_new_i32() {
entry:
  %p = call ptr @malloc(i32 8)
  %ready = getelementptr inbounds %promise.i32, ptr %p, i32 0, i32 0
  store i32 0, ptr %ready
  %value = getelementptr inbounds %promise.i32, ptr %p, i32 0, i32 1
  store i32 0, ptr %value
  ret ptr %p
}

define void @__sysy_promise_resolve_i32(ptr %p, i32 %v) {
entry:
  %value = getelementptr inbounds %promise.i32, ptr %p, i32 0, i32 1
  store i32 %v, ptr %value
  %ready = getelementptr inbounds %promise.i32, ptr %p, i32 0, i32 0
  store i32 1, ptr %ready
  ret void
}

define i32 @__sysy_promise_wait_i32(ptr %p) {
entry:
  %value = getelementptr inbounds %promise.i32, ptr %p, i32 0, i32 1
  %v = load i32, ptr %value
  ret i32 %v
}

define ptr @__sysy_promise_new_void() {
entry:
  %p = call ptr @malloc(i32 4)
  %ready = getelementptr inbounds %promise.void, ptr %p, i32 0, i32 0
  store i32 0, ptr %ready
  ret ptr %p
}

define void @__sysy_promise_resolve_void(ptr %p) {
entry:
  %ready = getelementptr inbounds %promise.void, ptr %p, i32 0, i32 0
  store i32 1, ptr %ready
  ret void
}

define void @__sysy_promise_wait_void(ptr %p) {
entry:
  ret void
}

define ptr @__sysy_sleep(i32 %duration) {
entry:
  %p = call ptr @__sysy_promise_new_void()
  call void @__sysy_promise_resolve_void(ptr %p)
  ret ptr %p
}

"#;
