// lalrpop 里的约定
grammar;
use compile_sysy::lalr::*;

match {
  r"\s*" => {},
  r"//[^\n\r]*[\n\r]*" => {},
  r"/\*([^*]|\*[^/])*\*/" => {},
  _
}

Ident: String = r"[_a-zA-Z][_a-zA-Z0-9]*" => <>.to_string();

IntConst: i32 = {
  r"[1-9][0-9]*" => i32::from_str_radix(<>, 10).unwrap(),
  r"0[0-7]*" => i32::from_str_radix(<>, 8).unwrap(),
  r"0[xX][0-9a-fA-F]+" => i32::from_str_radix(&<>[2..], 16).unwrap(),
}

pub CompUnit: CompUnit = <func_def: FuncDef> => CompUnit { func_def };

FuncDef: FuncDef = {
  <func_type: FuncType> <ident: Ident> "(" ")" <block: Block> => FuncDef { func_type, ident, block }
}

FuncType:
  FuncType = "int" => FuncType::Int;

Block: Block = "{" <stmts: StmtList> "}" => Block { stmts };

StmtList: Vec<Stmt> = {
  => Vec::new(),
  <stmt: Stmt> <rest: StmtList> => {
    let mut stmts = vec![stmt];
    stmts.extend(rest);
    stmts
  }
};

Stmt: Stmt = {
  <block: Block> => Stmt::Block(block),
  <ident: Ident> "=" <exp: Exp> ";" => Stmt::Assign(ident, exp),
  <typ: Type> <decls: MultipleDecl> ";" => Stmt::Decl(typ, decls),
  "return" <exp: Exp> ";" => Stmt::Return(<>),
  <exp: Exp> ";" => Stmt::Exp(exp),
  ";" => Stmt::Empty,
}

MultipleDecl: Vec<SingleDecl> = {
  <single_decl: SingleDecl> => vec![single_decl],
  <single_decl: SingleDecl> "," <rest: MultipleDecl> => {
    let mut decls = vec![single_decl];
    decls.extend(rest);
    decls
  }
}

SingleDecl: SingleDecl = {
  <ident: Ident> => SingleDecl { ident: ident, init: None },
  <ident: Ident> "=" <exp: Exp> => SingleDecl { ident: ident, init: Some(exp) },
}

BType: BType = "int" => BType::Int;

Type: Type = {
  "const" <btype: BType> => Type::Const(btype),
  <btype: BType> => Type::Var(btype),
}

Exp: Exp = {
  <exp: LOrExp> => exp,
}

PrimaryExp: Exp = {
  "(" <exp: Exp> ")" => exp,
  <int_const: IntConst> => Exp::Number(int_const),
  <ident: Ident> => Exp::Ident(ident),
}

UnaryExp: Exp = {
  <primary_exp: PrimaryExp> => primary_exp,
  <op: UnaryOp> <exp: UnaryExp> => Exp::UnaryExp(op, Box::new(exp)),
}

MulExp: Exp = {
  <unary_exp: UnaryExp> => unary_exp,
  <mul_exp: MulExp> <op: MulOp> <unary_exp: UnaryExp> => Exp::BinaryExp(op, Box::new(mul_exp), Box::new(unary_exp)),
}

AddExp: Exp = {
  <mul_exp: MulExp> => mul_exp,
  <add_exp: AddExp> <op: AddOp> <mul_exp: MulExp> => Exp::BinaryExp(op, Box::new(add_exp), Box::new(mul_exp)),
}

UnaryOp: UnaryOp = {
  "+" => UnaryOp::Pos,
  "-" => UnaryOp::Neg,
  "!" => UnaryOp::Not,
}

MulOp: BinaryOp = {
  "*" => BinaryOp::Mul,
  "/" => BinaryOp::Div,
  "%" => BinaryOp::Mod,
}

AddOp: BinaryOp = {
  "+" => BinaryOp::Add,
  "-" => BinaryOp::Sub,
}

RelExp: Exp = {
  <add_exp: AddExp> => add_exp,
  <rel_exp: RelExp> <op: RelOp> <add_exp: AddExp> => Exp::BinaryExp(op, Box::new(rel_exp), Box::new(add_exp)),
}

RelOp: BinaryOp = {
  "<" => BinaryOp::Lt,
  ">" => BinaryOp::Gt,
  "<=" => BinaryOp::Le,
  ">=" => BinaryOp::Ge,
}

EqExp: Exp = {
  <rel_exp: RelExp> => rel_exp,
  <eq_exp: EqExp> <op: EqOp> <rel_exp: RelExp> => Exp::BinaryExp(op, Box::new(eq_exp), Box::new(rel_exp)),
}

EqOp: BinaryOp = {
  "==" => BinaryOp::Eq,
  "!=" => BinaryOp::Ne,
}

LAndExp: Exp = {
  <eq_exp: EqExp> => eq_exp,
  <land_exp: LAndExp> "&&" <eq_exp: EqExp> => Exp::BinaryExp(BinaryOp::And, Box::new(land_exp), Box::new(eq_exp)),
}

LOrExp: Exp = {
  <land_exp: LAndExp> => land_exp,
  <lor_exp: LOrExp> "||" <land_exp: LAndExp> => Exp::BinaryExp(BinaryOp::Or, Box::new(lor_exp), Box::new(land_exp)),
}